export interface NutritionInfo {
  servingSize: string;
  calories?: number;
  protein?: string;
  carbs?: string;
  fat?: string;
  fiber?: string;
  iron?: string;
  calcium?: string;
  sodium?: string;
  sugar?: string;
  additionalNutrients?: { name: string; value: string }[];
  allergens: string[];
  dietaryInfo: string[];
  preparation?: string;
  storage?: string;
}

// Nutrition data keyed by product slug
export const nutritionData: Record<string, NutritionInfo> = {
  "pilau-spiced-up": {
    servingSize: "1 full combo (~450g)",
    calories: 620,
    protein: "28g",
    carbs: "72g",
    fat: "22g",
    fiber: "4g",
    iron: "15% DV",
    sodium: "680mg",
    allergens: ["None known"],
    dietaryInfo: ["High Protein", "No MSG", "Halal"],
    preparation: "Served hot. Ready to eat.",
    storage: "Best consumed fresh. Refrigerate leftovers within 2 hours.",
  },
  "rabbit-wet-fry": {
    servingSize: "1 full combo (~500g)",
    calories: 580,
    protein: "42g",
    carbs: "48g",
    fat: "18g",
    fiber: "6g",
    iron: "25% DV",
    calcium: "8% DV",
    allergens: ["None known"],
    dietaryInfo: ["High Protein", "Low Fat", "Iron-Rich"],
    preparation: "Served hot with greens and Ayola special ugali.",
    storage: "Best consumed fresh. Refrigerate leftovers within 2 hours.",
  },
  "turkey-eggs-afkeido": {
    servingSize: "1 full combo (~400g)",
    calories: 520,
    protein: "32g",
    carbs: "45g",
    fat: "20g",
    fiber: "3g",
    iron: "18% DV",
    allergens: ["Eggs", "Gluten (bread)"],
    dietaryInfo: ["High Protein", "Rich in B12", "Selenium-Rich"],
    preparation: "Served hot. Turkey eggs are larger and richer than chicken eggs.",
    storage: "Consume immediately for best quality.",
  },
  "vegan-combo": {
    servingSize: "1 full combo (~450g)",
    calories: 420,
    protein: "18g",
    carbs: "62g",
    fat: "12g",
    fiber: "10g",
    iron: "20% DV",
    allergens: ["None known"],
    dietaryInfo: ["Vegan", "Plant-Based", "High Fiber", "Cholesterol-Free"],
    preparation: "Served hot with heritage grains and seasonal vegetables.",
    storage: "Best consumed fresh.",
  },
  "plantain-kvass": {
    servingSize: "1 serving (~300ml)",
    calories: 65,
    protein: "0.5g",
    carbs: "16g",
    fat: "0g",
    fiber: "2g",
    sugar: "12g",
    allergens: ["None known"],
    dietaryInfo: ["Vegan", "Probiotic", "No Added Sugar", "Naturally Fermented"],
    additionalNutrients: [
      { name: "Live Probiotics", value: "Contains Lactobacillus strains" },
      { name: "Prebiotic Fiber", value: "From resistant starch" },
    ],
    preparation: "Serve chilled. Shake gently before opening — natural sediment is normal.",
    storage: "Refrigerate. Consume within 5 days of purchase. Contains live cultures.",
  },
  "synbiotic-porridge": {
    servingSize: "1 serving (~350ml)",
    calories: 180,
    protein: "6g",
    carbs: "34g",
    fat: "3g",
    fiber: "5g",
    iron: "30% DV",
    calcium: "12% DV",
    allergens: ["None known"],
    dietaryInfo: ["Vegetarian", "Synbiotic", "Heritage Grains", "Fermented"],
    additionalNutrients: [
      { name: "Probiotics", value: "Lactobacillus cultures" },
      { name: "Prebiotics", value: "Natural grain fiber" },
    ],
    preparation: "Served warm. Can be sweetened with honey to taste.",
    storage: "Consume fresh. Made daily at our kitchen.",
  },
  "goat-milk-tea": {
    servingSize: "1 cup (~250ml)",
    calories: 120,
    protein: "7g",
    carbs: "14g",
    fat: "5g",
    calcium: "25% DV",
    allergens: ["Dairy (goat milk)"],
    dietaryInfo: ["Vegetarian", "A2 Milk", "Easy to Digest"],
    preparation: "Served hot. Naturally sweetened with honey.",
    storage: "Consume fresh.",
  },
  "special-uji-drink": {
    servingSize: "1 serving (~300ml)",
    calories: 160,
    protein: "5g",
    carbs: "32g",
    fat: "2g",
    fiber: "4g",
    iron: "25% DV",
    allergens: ["May contain traces of milk"],
    dietaryInfo: ["Vegetarian", "Heritage Grains", "High Iron"],
    preparation: "Served warm with milk and honey.",
    storage: "Consume fresh.",
  },
  "ayola-ugali-blend": {
    servingSize: "100g (dry flour)",
    calories: 340,
    protein: "9g",
    carbs: "72g",
    fat: "3g",
    fiber: "6g",
    iron: "35% DV",
    calcium: "8% DV",
    allergens: ["May contain traces of sorghum, millet"],
    dietaryInfo: ["Vegan", "No Preservatives", "Fortified", "Ships Countrywide"],
    preparation: "Mix with boiling water to make ugali. Ratio: 1 cup flour to 2.5 cups water. Also great for healthier bread — substitute 30-50% of wheat flour.",
    storage: "Store in a cool, dry place. Seal tightly after opening. Best within 6 months.",
  },
  "ayola-uji-blend": {
    servingSize: "100g (dry flour)",
    calories: 360,
    protein: "11g",
    carbs: "68g",
    fat: "4g",
    fiber: "8g",
    iron: "40% DV",
    calcium: "15% DV",
    allergens: ["None known"],
    dietaryInfo: ["Vegan", "Heritage Grains", "Gut-Friendly", "Ships Countrywide"],
    additionalNutrients: [
      { name: "Finger Millet", value: "Rich in calcium & iron" },
      { name: "Sorghum", value: "Gluten-free, high in antioxidants" },
      { name: "Amaranth", value: "Complete protein source" },
    ],
    preparation: "Mix 3 tbsp with cold water to make a paste. Pour into 2 cups boiling water, stir continuously. Cook 8-10 mins. Add milk and honey to taste. For fermented version: mix with warm water, cover, and ferment 24-48 hours.",
    storage: "Store in cool, dry place. Seal after opening. Best within 6 months.",
  },
  "custom-flour-blend": {
    servingSize: "Varies",
    allergens: ["Varies based on formulation — discuss with our food scientist"],
    dietaryInfo: ["Custom Formulation", "Made to Order"],
    preparation: "Instructions provided with each custom order.",
    storage: "Store in cool, dry place.",
  },
  "healthy-breakfast": {
    servingSize: "1 full breakfast",
    calories: 450,
    protein: "22g",
    carbs: "52g",
    fat: "16g",
    fiber: "5g",
    allergens: ["Eggs", "Gluten (bread)"],
    dietaryInfo: ["Balanced", "Whole Grains", "Fresh Ingredients"],
    preparation: "Served hot. Varies daily based on seasonal ingredients.",
    storage: "Consume immediately.",
  },
  "heavy-meal-combo": {
    servingSize: "1 heavy combo (~600g)",
    calories: 780,
    protein: "45g",
    carbs: "68g",
    fat: "28g",
    fiber: "7g",
    iron: "30% DV",
    allergens: ["Varies by protein choice"],
    dietaryInfo: ["High Protein", "Full Meal", "Balanced Nutrition"],
    preparation: "Served hot with premium protein, special ugali, vegetables, side, and beverage.",
    storage: "Consume immediately for best quality.",
  },
};
